---
- hosts: localhost
  pre_tasks:
    - name: Verify Ansible version requirements
      assert:
        that: "ansible_version.full | version_compare('2.0', '>=')"
        msg: "Ansible version 2.0 or higher is required to run this playbook"

- hosts: test_switches
  user: admin
  become: yes
  become_method: sudo
  roles:
    - network_alt_rcnet

- hosts: test_servers
  user: admin
  become: yes
  become_method: sudo
  roles:
    - network_centos
